//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynago.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dynago.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace /*rnd*/DynagoStub/*rnd*/ {
        ///
        ///    static class /*rnd*/cl_AimbotMath/*rnd*/  {
        ///
        ///        /*order-start*/
        ///        /*junk_method*/
        ///
        ///        /*order-*/
        ///        public struct /*rnd*/str_Vector3/*rnd*/  {
        ///            /*order-start*/
        ///            /*order-*/public float /*rnd*/var_Xc/*rnd*/;/*order-*/
        ///            /*order-*/public float /*rnd*/var_Yc/*rnd*/;/*order-*/
        ///            /*order-*/public float /*rnd*/var_Zc/*rnd*/;/*order-*/
        ///            /*order-end*/
        ///        }
        ///        /*order-*/
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AimbotMath {
            get {
                return ResourceManager.GetString("AimbotMath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project outputDir=&quot;[directory]&quot; baseDir=&quot;[directory]&quot; xmlns=&quot;http://confuser.codeplex.com&quot;&gt;
        ///  &lt;module path=&quot;[filename]&quot;&gt;
        ///    &lt;rule pattern=&quot;true&quot; preset=&quot;[preset]&quot; inherit=&quot;false&quot; /&gt;
        ///  &lt;/module&gt;
        ///&lt;/project&gt;.
        /// </summary>
        internal static string CRproj {
            get {
                return ResourceManager.GetString("CRproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace /*rnd*/DynagoStub/*rnd*/
        ///{
        ///
        ///    using System;
        ///    using System.Diagnostics;
        ///    using System.Runtime.InteropServices;
        ///
        ///    class /*rnd*/cl_Memory/*rnd*/
        ///    {
        ///        /*order-start*/
        ///        /*junk_method*/
        ///        /*order-*/
        ///        public static bool /*rnd*/met_InitializeCSGO/*rnd*/()
        ///        {
        ///            /*junk_line*/
        ///            Process /*rnd*/var_Process/*rnd*/;
        ///            if (Process.GetProcessesByName(&quot;csgo&quot;).Length &gt; 0) /*rnd*/var_Process/*rnd*/ = Process.GetProcessesByNa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace /*rnd*/DynagoStub/*rnd*/
        ///{
        ///    class /*rnd*/cl_Offsets/*rnd*/ 
        ///    {
        ///        /*junk_method*/
        ///        /*order-start*/
        ///        /*order-*/public static int /*rnd*/var_offset_LocalPlayer/*rnd*/ = /*number*//*offset_LocalPlayer*/0xA9ADEC/*offset_LocalPlayer*//*number*/;/*order-*/
        ///        /*order-*/public static int /*rnd*/var_offset_Health/*rnd*/ = /*number*//*offset_Health*/0xFC/*offset_Health*//*number*/;/*order-*/
        ///        /*order-*/public static int /*rnd*/var_offset_Team/*rnd*/ = /*number*/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Offsets {
            get {
                return ResourceManager.GetString("Offsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace /*rnd*/DynagoStub/*rnd*/
        ///{
        ///    using System;
        ///    using System.Linq;
        ///    using System.Runtime.InteropServices;
        ///    using System.Threading;
        ///    class Program
        ///    {
        ///        /*junk_method*/
        ///        [DllImport(&quot;user32.dll&quot;)]
        ///        public static extern short GetAsyncKeyState(int var_Key);
        ///        /*junk_method*/
        ///        public static int
        ///            /*rnd*/var_LocalPlayer/*rnd*/ = 0,
        ///            /*rnd*/var_LocalPlayer_Team/*rnd*/  = 0,
        ///            /*rnd*/var_LocalPlayer_Health/*rnd*/  = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
    }
}
